### ISSUE TITLE
Timeout while executing a shell script

### ISSUE THREAD

**Issue by mammuthus** [romainsi/zabbix-dhcp_scope#1]
Getting error after implementing;
` 23058:20190207:121220.022 error reason for "srv:dhcp["Discovery"]" changed: Timeout while executing a shell script.`
But time is enought to execute.
Zabbix 4.0.2

**Comment by mammuthus** [comment]
It was my fault, sorry
Issue closed.

**Comment by kirpozh** [comment]
@mammuthus 
Hi, I understand that it was a long time ago, but I just ran into the same error. If you remember, will you tell me what was in your case?

**Comment by mammuthus** [comment]
> @mammuthus Hi, I understand that it was a long time ago, but I just ran into the same error. If you remember, will you tell me what was in your case?

Frankly, I don't remember. I guess there was an error in my original script.
